lab :
	gcc -c ./src/main.c -o ./bin/main.o -lm
	gcc -c ./src/simple_neural_networks.c -o ./bin/simple_neural_networks.o -lm 
	gcc -o ./bin/lab1 ./bin/main.o ./bin/simple_neural_networks.o -lm

clean : 
	rm */bin/*.o

clear :
	rm */bin/*