lab :
	gcc -c ./Lab4_1_PC_backpropagation/src/main.c -o ./Lab4_1_PC_backpropagation/bin/main.o -lm
	gcc -c ./Lab4_1_PC_backpropagation/src/simple_neural_networks.c -o ./Lab4_1_PC_backpropagation/bin/simple_neural_networks.o -lm 
	gcc -o ./Lab4_1_PC_backpropagation/bin/lab4 ./Lab4_1_PC_backpropagation/bin/main.o ./Lab4_1_PC_backpropagation/bin/simple_neural_networks.o -lm

clean : 
	rm */bin/*.o

clear :
	rm */bin/*