lab1 :
	gcc -Wall -c ./Lab1_1/src/main.c -o ./Lab1_1/bin/main.o
	gcc -Wall -c ./Lab1_1/src/simple_neural_networks.c -o ./Lab1_1/bin/simple_neural_networks.o
	gcc -Wall -o ./Lab1_1/bin/lab1 ./Lab1_1/bin/main.o ./Lab1_1/bin/simple_neural_networks.o

lab2 :
	gcc -Wall -c ./Lab1_2/src/main.c -o ./Lab1_2/bin/main.o
	gcc -Wall -c ./Lab1_2/src/simple_neural_networks.c -o ./Lab1_2/bin/simple_neural_networks.o
	gcc -Wall -o ./Lab1_2/bin/lab2 ./Lab1_2/bin/main.o ./Lab1_2/bin/simple_neural_networks.o

lab3 :
	gcc -Wall -c ./Lab1_3/src/main.c -o ./Lab1_3/bin/main.o
	gcc -Wall -c ./Lab1_3/src/simple_neural_networks.c -o ./Lab1_3/bin/simple_neural_networks.o
	gcc -Wall -o ./Lab1_3/bin/lab3 ./Lab1_3/bin/main.o ./Lab1_3/bin/simple_neural_networks.o

lab4 :
	gcc -Wall -c ./Lab1_4/src/main.c -o ./Lab1_4/bin/main.o
	gcc -Wall -c ./Lab1_4/src/simple_neural_networks.c -o ./Lab1_4/bin/simple_neural_networks.o
	gcc -Wall -o ./Lab1_4/bin/lab4 ./Lab1_4/bin/main.o ./Lab1_4/bin/simple_neural_networks.o

all :
	gcc -Wall -c ./Lab1_1/src/main.c -o ./Lab1_1/bin/main.o
	gcc -Wall -c ./Lab1_1/src/simple_neural_networks.c -o ./Lab1_1/bin/simple_neural_networks.o
	gcc -Wall -c ./Lab1_2/src/main.c -o ./Lab1_2/bin/main.o
	gcc -Wall -c ./Lab1_2/src/simple_neural_networks.c -o ./Lab1_2/bin/simple_neural_networks.o
	gcc -Wall -c ./Lab1_3/src/main.c -o ./Lab1_3/bin/main.o
	gcc -Wall -c ./Lab1_3/src/simple_neural_networks.c -o ./Lab1_3/bin/simple_neural_networks.o
	gcc -Wall -c ./Lab1_4/src/main.c -o ./Lab1_4/bin/main.o
	gcc -Wall -c ./Lab1_4/src/simple_neural_networks.c -o ./Lab1_4/bin/simple_neural_networks.o
	gcc -Wall -o ./Lab1_1/bin/lab1 ./Lab1_1/bin/main.o ./Lab1_1/bin/simple_neural_networks.o
	gcc -Wall -o ./Lab1_2/bin/lab1 ./Lab1_2/bin/main.o ./Lab1_2/bin/simple_neural_networks.o
	gcc -Wall -o ./Lab1_3/bin/lab1 ./Lab1_3/bin/main.o ./Lab1_3/bin/simple_neural_networks.o
	gcc -Wall -o ./Lab1_4/bin/lab1 ./Lab1_4/bin/main.o ./Lab1_4/bin/simple_neural_networks.o

clean : 
	rm */bin/*.o

clear :
	rm */bin/*