lab :
	gcc -c ./Lab3_1_PC_feedforward/src/main.c -o ./Lab3_1_PC_feedforward/bin/main.o -lm
	gcc -c ./Lab3_1_PC_feedforward/src/simple_neural_networks.c -o ./Lab3_1_PC_feedforward/bin/simple_neural_networks.o -lm 
	gcc -o ./Lab3_1_PC_feedforward/bin/lab1 ./Lab3_1_PC_feedforward/bin/main.o ./Lab3_1_PC_feedforward/bin/simple_neural_networks.o -lm

clean : 
	rm */bin/*.o

clear :
	rm */bin/*